# Generated by Django 2.0.6 on 2020-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='press',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RemoveField(
            model_name='authordetail',
            name='id_delete',
        ),
        migrations.AddField(
            model_name='authordetail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
