# Generated by Django 2.0.6 on 2020-10-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(db_constraint=False, related_name='books', to='api.Author'),
        ),
    ]
