# Generated by Django 2.0.6 on 2020-10-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201030_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(default='img/1.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='press',
            name='pic',
            field=models.ImageField(default='img/1.jpg', upload_to='img'),
        ),
        migrations.AlterModelTable(
            name='press',
            table='bz_press',
        ),
    ]
